### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by danielgomezrico** [algolia/algoliasearch-client-kotlin#172]
Im getting an error on build after updating the dependencies versions.

# Dependencies that builds fine

```
    implementation 'com.algolia:algoliasearch-android:3.27.0'
    implementation "com.algolia:algoliasearch-client-kotlin-jvm:1.1.4"
    implementation 'com.algolia:instantsearch-android:2.0.2'
```

# Dependencies with bug on compile

```
implementation 'com.algolia:algoliasearch-android:3.27.0'
implementation "com.algolia:algoliasearch-client-kotlin-jvm:1.3.1"
implementation 'com.algolia:instantsearch-android:2.3.1'
````

# Error stacktrace
I get this error:

```
Duplicate class BuildConfig found in modules algoliasearch-client-kotlin-android-1.3.1-runtime.jar (com.algolia:algoliasearch-client-kotlin-android:1.3.1) and algoliasearch-client-kotlin-jvm-1.3.1.jar (com.algolia:algoliasearch-client-kotlin-jvm:1.3.1)
Duplicate class com.algolia.search.client.ClientAccount found in modules algoliasearch-client-kotlin-android-1.3.1-runtime.jar (com.algolia:algoliasearch-client-kotlin-android:1.3.1) and algoliasearch-client-kotlin-jvm-1.3.1.jar (com.algolia:algoliasearch-client-kotlin-jvm:1.3.1)
...
```

**Comment by Aallam** [comment]
Hello @danielgomezrico, `instantsearch-android` now depends on `algoliasearch-client-kotlin-android` instead of `algoliasearch-client-kotlin-jvm`. You can solve this issue by either:

- Replacing `com.algolia:algoliasearch-client-kotlin-jvm:1.3.1` by `com.algolia:algoliasearch-client-kotlin-android:1.3.1`, OR
- Deleting the explicit kotlin client dependency declaration, `instantsearch-android` already depends on the correct library and exposes it to you.

**Comment by danielgomezrico** [comment]
@Aallam thanks! it worked, I ended up using:

```
implementation 'com.algolia:algoliasearch-android:3.27.0'
implementation 'com.algolia:instantsearch-android:2.3.1'
```
