### ISSUE TITLE
setup okhttp instance

### ISSUE THREAD

**Issue by CoreFloDev** [algolia/algoliasearch-client-kotlin#276]
Hi,

I would like to use the same okhttp instance I am already using in my app with algolia. I had a look at the `engine` parameter of that function
```kotlin
ClientInsights(ConfigurationInsights(appId, apiKey, engine = OkHttpEngine))
```
But I can't find the way to set an existing okhttp instance to that function and the other parameters don't seems to be designed for that.

Thanks,
Flo

**Comment by CoreFloDev** [comment]
Hi @Aallam,

Any update on this?

Thanks!
Flo

**Comment by Aallam** [comment]
Hi @CoreFloDev, there is no direct way of doing this right now; this is something we may improve later on.
Meanwhile, you can use something like this:
```kotlin
val myOkHttpClient = OkHttpClient()
    val client = ClientSearch(
        configuration = ConfigurationSearch(
            applicationID = ApplicationID("MyApplicationID"),
            apiKey = APIKey("MyAPIKey"),
            httpClientConfig = {
                @Suppress("UNCHECKED_CAST")
                val okHttpClientConfig = this as HttpClientConfig<OkHttpConfig>
                okHttpClientConfig.engine {
                    preconfigured = myOkHttpClient
                }
            }
        )
    )
```
I hope this helps.

PS: because of `this as HttpClientConfig<OkHttpConfig>`, please make sure to have the correct Ktor client dependency, otherwise, an error may be thrown at runtime.

**Comment by CoreFloDev** [comment]
yes that seemed to work thanks!
